export default [
    { name: "Proteínas", label: "Prot." },
    { name: "Calorías", label: "kCal" },
    { name: "Carbohidratos", label: "Carb." },
    { name: "Fibras", label: "Fib." },
    { name: "Sodio", label: "Sod." },
    { name: "Calcio", label: "Calc." },
    { name: "Potasio", label: "Pot." },
    { name: "Fósforo", label: "Fosf." },
    { name: "Hierro", label: "Hierro" },
    { name: "Zinc", label: "Zinc" },
    { name: "Tiamina", label: "Tiam." },
    { name: "Rivoflavina", label: "Rivof." },
    { name: "Niacina", label: "Niac." },
    { name: "Vitamina_C", label: "Vit. C" },
    { name: "Energía", label: "Energ." },
    { name: "Agua", label: "Agua" },
    { name: "Grasa", label: "Grasa" },
    { name: "Monoinsaturada", label: "Mono" },
    { name: "Poliinsaturada", label: "Poli" },
    { name: "Colesterol", label: "Col." },
    { name: "Saturada", label: "G. Sat." },
  ];